#
# Makefile for the linux arm-specific parts of the memory manager.
#

#obj-$(CONFIG_CPU_CACHE_V7)	+= cache-v7.o
#obj-$(CONFIG_CPU_TLB_V7)	+= tlb-v7.o
#obj-$(CONFIG_CPU_V7)		+= proc-v7.o

obj-y += memory.o
obj-y += page_alloc.o
obj-y += xmalloc_tlsf.o
obj-y += percpu.o
obj-y += fault.o

