
obj-y += boot/

obj-y += spinlock.o

obj-y += fault.o backtrace.o
obj-y += backtrace.o backtrace_asm.o
obj-y += setup.o mmu.o cache_v8.o cache.o context.o domain.o

#obj-y += setup.o exception.o hypercalls.o context.o
#obj-y += cache_v7_asm.o cache_v7.o cache-cp15.o
#obj-y += boot/ 
#obj-y += mmu.o

obj-y += lib/

#obj-y += $(TARGET)/

