#
# Makefile for some libs needed in the kernel.
#

lib-y += ashldi3.o delay.o memset.o memchr.o memzero.o \
	 memcpy.o memmove.o setbit.o strchr.o \
	 ashrdi3.o lshrdi3.o div64.o lib1funcs.o muldi3.o testchangebit.o \
	 udivdi3.o clearbit.o findbit.o testclearbit.o backtrace.o _uldivmod.o \
	 changebit.o crc32.o

lib-y += domain_utils.o logbool.o

lib-y += image-fit.o 


