#
# Makefile for some libs needed in the kernel.
#
lib-y += string.o vsprintf.o ctype.o string_helpers.o
#lib-y += memzero.o ashldi3.o delay.o memchr.o  \
	 setbit.o \
	 ashrdi3.o lshrdi3.o div64.o lib1funcs.o muldi3.o testchangebit.o \
	 udivdi3.o clearbit.o findbit.o testclearbit.o _uldivmod.o \
	 changebit.o crc32.o

lib-y += domain_utils.o logbool.o image-fit.o

#lib-y += eabi_compat.o


