
obj-$(CONFIG_SOO_REFSO3) += refso3/
obj-$(CONFIG_SOO_OUTDOOR) += outdoor/
obj-$(CONFIG_SOO_BLIND) += blind/
obj-$(CONFIG_SOO_AGENCY) += agency/
obj-$(CONFIG_SOO_NET) += net/

obj-y += eco_stability.o



