image: alpine

variables:
    GIT_DEPTH: 1

pages:
    stage: deploy
    script:
    - apk --no-cache add py3-pip python3-dev
    - pip3 install sphinx
    - pip3 install sphinx_rtd_theme
    - pip3 install sphinxcontrib-plantuml
    - pip3 install sphinxcontrib-bibtex
    - apk --no-cache add make
    - cd doc
    - make html
    - mv build/html/ ../public/
    artifacts:
        paths:
        - public
    only:
    - master
