
obj-y += setup.o exception.o fault.o hypercalls.o context.o
obj-y += cache_v7_asm.o cache_v7.o cache-cp15.o
obj-y += boot/ 
obj-y += mmu.o
obj-y += vfp.o
obj-y += backtrace.o backtrace_asm.o

obj-y += lib/

obj-$(CONFIG_PSCI) += smccc-call.o

obj-y += $(TARGET)/

