#
# -- SOO Hypervisor Technology --
#
# Emails: {firstname.lastname}@heig-vd.ch
# Copyright (c) 2007-2015 Reconfigurable Embedded Digital Systems (REDS) Institute at HEIG-VD, Switzerland
#
#

obj-$(CONFIG_VFB_BACKEND) := vfbback.o

vfbback-y := vfb.o vbus.o 
