

ifeq ($(CONFIG_SOO_REFSO3),y)

ifeq ($(CONFIG_RAMDEV),y)
dtb-y += refso3_ramfs.dtb
else
dtb-y += refso3.dtb
endif

endif

dtb-$(CONFIG_SOO_OUTDOOR) += outdoor.dtb
dtb-$(CONFIG_SOO_BLIND) += blind.dtb
dtb-$(CONFIG_SOO_AGENCY) += agency.dtb
dtb-$(CONFIG_SOO_NET) += net.dtb
dtb-$(CONFIG_SOO_LEDCTRL) += ledctrl.dtb


