obj-y += plugin.o

obj-$(CONFIG_SOOLINK_PLUGIN_WLAN) += wlan.o
obj-$(CONFIG_SOOLINK_PLUGIN_ETHERNET) += ethernet.o
obj-$(CONFIG_SOOLINK_PLUGIN_BLUETOOTH) += bluetooth.o
obj-$(CONFIG_SOOLINK_PLUGIN_LOOPBACK) += loopback.o

obj-$(CONFIG_SOOLINK_PLUGIN_SIMULATION) += simulation.o
