obj-$(CONFIG_VDUMMY_FRONTEND) += vdummyfront/
obj-$(CONFIG_VUART_FRONTEND) += vuartfront/
obj-$(CONFIG_VDOGA12V6NM_FRONTEND) += vdoga12v6nmfront/
obj-$(CONFIG_VWEATHER_FRONTEND) += vweatherfront/
obj-$(CONFIG_VUIHANDLER_FRONTEND) += vuihandlerfront/
