
// SPDX-License-Identifier: BSD-2-Clause
/*
 * Copyright (C) 2020 Jean-Pierre Miceli <jean-pierre.miceli@heig-vd.ch>
 */

/* File generated by './gen_sym_key.py' tool */

#define ASF_COM_KEY		"c3da43e8d5e228abfe9b6733b809ecd5ab7955ef7d80b3de6293a03e3cd37a8f"

