
// SPDX-License-Identifier: BSD-2-Clause
/*
 * Copyright (C) 2020 Jean-Pierre Miceli <jean-pierre.miceli@heig-vd.ch>
 */

/* File generated by './gen_sym_key.py' tool */

#define ASF_INJECT_KEY		"pttPr8YBqCBSaeHE2x0HChtS/wsRDmviOLO1QcAyUEI="

