
// SPDX-License-Identifier: BSD-2-Clause
/*
 * Copyright (C) 2020 Jean-Pierre Miceli <jean-pierre.miceli@heig-vd.ch>
 */

/* File generated by './gen_sym_key.py' tool */

#define ASF_COM_KEY		"08WyHLAxVuzKGDAjuxBltu40rXk9mC9+1cikJuxlbWI="

