
// SPDX-License-Identifier: BSD-2-Clause
/*
 * Copyright (C) 2020 Jean-Pierre Miceli <jean-pierre.miceli@heig-vd.ch>
 */

/* File generated by './gen_sym_key.py' tool */

#define ASF_COM_KEY		"vVzZb/hvLfylI0floQsXMb4sLZzVrRVxx56AIxWxheM="

