
// SPDX-License-Identifier: BSD-2-Clause
/*
 * Copyright (C) 2020 Jean-Pierre Miceli <jean-pierre.miceli@heig-vd.ch>
 */

/* File generated by './gen_sym_key.py' tool */

#define ASF_INJECT_KEY		"839ac79f31251e61a8223ae623ab7d6411acaa8d1a4e003e28370df546dfb3cb"

