
obj-y += gpio.o time.o dbgvar.o meminfo.o logbool.o dbglib.o dbgvar.o
#obj-$(CONFIG_SOO_AGENCY)	+= bandwidth.o bandwidth_neon.o
#CFLAGS_bandwidth_neon.o		:= -mfpu=neon -mfloat-abi=softfp -ffreestanding
