obj-$(CONFIG_XENOMAI) += xenomai.o rtdm/ 

xenomai-y :=	arith.o 	\
		clock.o		\
		heap.o		\
		init.o		\
		intr.o		\
		lock.o		\
		sched-idle.o	\
		registry.o      \
		sched-rt.o	\
		sched.o		\
		select.o	\
		synch.o		\
		thread.o	\
		timer.o		\
		tree.o

 
