#
# Makefile for SOO general drivers.
#

obj-y += vdevback.o

obj-$(CONFIG_VDUMMY_BACKEND) += vdummyback/ 
obj-$(CONFIG_VDOGA12V6NM_BACKEND) += vdoga12v6nmback/
obj-$(CONFIG_VWEATHER_BACKEND)	+= vweatherback/
obj-$(CONFIG_VUART_BACKEND) += vuartback/
obj-$(CONFIG_VUIHANDLER_BACKEND) += vuihandlerback/
obj-$(CONFIG_VINPUT_BACKEND)	+= vinputback/
obj-$(CONFIG_VLEDS_BACKEND)		+= vledsback/
obj-$(CONFIG_VFB_BACKEND)  += vfbback/
obj-$(CONFIG_VNET_BACKEND)  += vnetback/
obj-$(CONFIG_VSENSELED_BACKEND) += vsenseledback/
obj-$(CONFIG_VSENSEJ_BACKEND) += vsensejback/
obj-$(CONFIG_VWAGOLED_BACKEND) += vwagoledback/
