obj-y += vdevfront.o

obj-$(CONFIG_VDUMMY_FRONTEND) 		+= vdummyfront/
obj-$(CONFIG_VUART_FRONTEND) 		+= vuartfront/
obj-$(CONFIG_VDOGA12V6NM_FRONTEND) 	+= vdoga12v6nmfront/
obj-$(CONFIG_VWEATHER_FRONTEND) 	+= vweatherfront/
obj-$(CONFIG_VUIHANDLER_FRONTEND) 	+= vuihandlerfront/
obj-$(CONFIG_VSENSELED_FRONTEND) 	+= vsenseledfront/
obj-$(CONFIG_VSENSEJ_FRONTEND) 		+= vsensejfront/
obj-$(CONFIG_VENOCEAN_FRONTEND) 	+= venoceanfront/
obj-$(CONFIG_VWAGOLED_FRONTEND) 	+= vwagoledfront/
obj-$(CONFIG_VTEMP_FRONTEND) 		+= vtempfront/
obj-$(CONFIG_VVALVE_FRONTEND) 		+= vvalvefront/
obj-$(CONFIG_VDOGABLIND_FRONTEND) 	+= vdogablindfront/